### ISSUE TITLE
WordWrap crashes when used before text has been set / control has been added

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1197]
Not sure if this is to do with the Fill or because control hasn't been rendered yet but word wrap causes crash for me (in master) when setting it prior to adding to control.

```csharp
Top.Add (new TextView () { Width = Dim.Fill(), WordWrap = true });
```

Exception:
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values. (Parameter 'width cannot be negative')
  Source=Terminal.Gui
  StackTrace:
   at Terminal.Gui.TextFormatter.Format(ustring text, Int32 width, TextAlignment talign, Boolean wordWrap, Boolean preserveTrailingSpaces) in Z:\Repos\gui.cs\Terminal.Gui\Core\TextFormatter.cs:line 344
   at Terminal.Gui.WordWrapManager.WrapModel(Int32 width, Int32& nRow, Int32& nCol, Int32& nStartRow, Int32& nStartCol, Int32 row, Int32 col, Int32 startRow, Int32 startCol) in Z:\Repos\gui.cs\Terminal.Gui\Views\TextView.cs:line 324
   at Terminal.Gui.TextView.set_WordWrap(Boolean value) in Z:\Repos\gui.cs\Terminal.Gui\Views\TextView.cs:line 779
   at UICatalog.Scenarios.GraphViewExample.Setup() in Z:\Repos\gui.cs\UICatalog\Scenarios\GraphViewExample.cs:line 29
   at UICatalog.UICatalogApp.Main(String[] args) in Z:\Repos\gui.cs\UICatalog\UICatalog.cs:line 108
```

**Comment by BDisp** [comment]
Because in the `WordWrap `property I did the follow:

`model = wrapManager.WrapModel (Frame.Width - 2, out _, out _, out _, out _);`

Normally, this is no big deal because we generally do not add views directly at the top but through a `Window `toplevel. But I'll do the follow change to mitigate this:

`model = wrapManager.WrapModel (Math.Max (Frame.Width - 2, 0), out _, out _, out _, out _);`

**Comment by BDisp** [comment]
If you use it with a `MenuBar `and a `StatusBar `you will see unexpected behavior, because only the `Window `can deal with all that.
