### ISSUE TITLE
ScrollView: Scrolling horizontally leads to IndexOutOfRangeException

### ISSUE THREAD

**Issue by Biliban** [migueldeicaza/gui.cs#1250]
Precondition: Having Content (e.g. Label) in a ScrollView

![Example](https://user-images.githubusercontent.com/34793814/116208733-7f933a00-a741-11eb-850a-df25b913b5f0.GIF)

Scroll horizontally until the Content leaves the Console Window and an IndexOutOfRangeException is thrown:

````
Index was outside the bounds of the array.
   at Terminal.Gui.TextFormatter.Draw(Rect bounds, Attribute normalColor, Attribute hotColor)
   at Terminal.Gui.View.Redraw(Rect bounds)
   at Terminal.Gui.View.Redraw(Rect bounds)
   at Terminal.Gui.ScrollView.Redraw(Rect region)
   at Terminal.Gui.View.Redraw(Rect bounds)
   at Terminal.Gui.FrameView.Redraw(Rect bounds)
   at Terminal.Gui.View.Redraw(Rect bounds)
   at Terminal.Gui.Toplevel.Redraw(Rect bounds)
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
````

**Comment by BDisp** [comment]
I can't repro this anymore. This commit 4948d072 already fixed it. Are you sure you have the last `Terminal.Gui` version?

**Comment by Biliban** [comment]
Indeed I was using Nuget Package (1.0.0-rc.1). Retested with 1.0.0-rc.8 and its working! Sorry for the inconvenience ^^

**Comment by ttool22** [comment]
It doesn't work in the latest version (1.7.2)

**Comment by tznind** [comment]
> It doesn't work in the latest version (1.7.2)

Hi, thanks for reaching out.  Could you please provide some background to exactly what doesn't work?

Do you get this `IndexOutOfRangeException` in all scroll views in your application or only specific ones?  

You mention 1.7.2 specifically, did you have scroll view working with 1.7.1 (or an earlier version) and it stopped working after update?

Are you able to provide any code that shows how you are using the scroll view?

**Comment by ttool22** [comment]
I am using combobox control, when I delete characters It throws the same error **IndexOutOfRangeException**
