### ISSUE TITLE
ListView scrolling with PageDown results in System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by rmorales87atx** [migueldeicaza/gui.cs#1326]
Scrolling down a ListView by holding the `Page Down` key in a large list eventually results in `System.ArgumentOutOfRangeException`.

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at Terminal.Gui.ListView.OnSelectedChanged() in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Views\ListView.cs:line 636
   at Terminal.Gui.ListView.MovePageDown() in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Views\ListView.cs:line 479
   at Terminal.Gui.ListView.ProcessKey(KeyEvent kb) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Views\ListView.cs:line 384
   at Terminal.Gui.View.ProcessKey(KeyEvent keyEvent) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\View.cs:line 1486
   at Terminal.Gui.View.ProcessKey(KeyEvent keyEvent) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\View.cs:line 1486
   at Terminal.Gui.View.ProcessHotKey(KeyEvent keyEvent) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\View.cs:line 1502
   at Terminal.Gui.Application.ProcessKeyEvent(KeyEvent ke) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 307
   at Terminal.Gui.WindowsDriver.ProcessInput(InputRecord inputEvent) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\ConsoleDrivers\WindowsDriver.cs:line 762
   at Terminal.Gui.WindowsDriver.<PrepareToRun>b__31_0(InputRecord e) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\ConsoleDrivers\WindowsDriver.cs:line 661
   at Terminal.Gui.WindowsMainLoop.Terminal.Gui.IMainLoopDriver.MainIteration() in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\ConsoleDrivers\WindowsDriver.cs:line 1634
   at Terminal.Gui.MainLoop.MainIteration() in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\MainLoop.cs:line 238
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 645
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 737
   at Terminal.Gui.Application.Run(Func`2 errorHandler) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 687
   at Cashbox.Screen.Activate() in E:\cashbox_cs\common\UiScreen.cs:line 55
   at Cashbox.UI.ShowScreen[T](Object[] args) in E:\cashbox_cs\common\UiTools.cs:line 98
   at config.ViewMenu.<>c.<OnActivate>b__6_3() in E:\cashbox_cs\config\ViewMenu.cs:line 39
   at config.ViewMenu.OnOpenSelectedItem(ListViewItemEventArgs args) in E:\cashbox_cs\config\ViewMenu.cs:line 64
   at Terminal.Gui.ListView.OnOpenSelectedItem() in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Views\ListView.cs:line 659
   at Terminal.Gui.ListView.MouseEvent(MouseEvent me) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Views\ListView.cs:line 751
   at Terminal.Gui.View.OnMouseEvent(MouseEvent mouseEvent) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\View.cs:line 2186
   at Terminal.Gui.Application.ProcessMouseEvent(MouseEvent me) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 472
   at Terminal.Gui.WindowsDriver.ProcessInput(InputRecord inputEvent) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\ConsoleDrivers\WindowsDriver.cs:line 773
   at Terminal.Gui.WindowsDriver.<PrepareToRun>b__31_0(InputRecord e) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\ConsoleDrivers\WindowsDriver.cs:line 661
   at Terminal.Gui.WindowsMainLoop.Terminal.Gui.IMainLoopDriver.MainIteration() in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\ConsoleDrivers\WindowsDriver.cs:line 1634
   at Terminal.Gui.MainLoop.MainIteration() in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\MainLoop.cs:line 238
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 645
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 737
   at Terminal.Gui.Application.Run(Func`2 errorHandler) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 687
   at Cashbox.Screen.Activate() in E:\cashbox_cs\common\UiScreen.cs:line 55
   at Cashbox.UI.ShowScreen[T](Object[] args) in E:\cashbox_cs\common\UiTools.cs:line 98
   at config.Program.Main(String[] args) in E:\cashbox_cs\config\Program.cs:line 19
```

A minor change to `ListView.cs` line 636 would appear to resolve the issue:
``` C#
var value = source?.Count > 0 && selected < source?.Count ? source.ToList () [selected] : null;
```

**Comment by tznind** [comment]
Hmn so the change you are proposing would not solve the underlying issue of the int `selected` being outside the bounds of the underlying list.  

https://github.com/migueldeicaza/gui.cs/blob/26cb2007372670aaf6b0acf97985893c694f44f7/Terminal.Gui/Views/ListView.cs#L635-L640

The code in `MovePageDown` already has a conditional `n > source.Count` to prevent the index going outside of bounds.

https://github.com/migueldeicaza/gui.cs/blob/26cb2007372670aaf6b0acf97985893c694f44f7/Terminal.Gui/Views/ListView.cs#L468-L481

Are you using a custom `IListDataSource` or making changes to the list content in real time that might result in the bounds changing during scrolling? 

Are you able to create a minimal reproduction of this issue? The UICatalog.exe Scenario `ListView & ComboBox` has a large list in it and I cannot replicate the behaviour you are seeing.

![image](https://user-images.githubusercontent.com/31306100/120167652-e8b11600-c1f5-11eb-972f-87aa859e2600.png)

**Comment by rmorales87atx** [comment]
Simplified test case that raises the issue for me:

``` C#
var list = new ListView() {
	Y = 10,
	X = 0,
	Height = Dim.Sized(10),
	Width = Dim.Fill(),
};
var items = new List<string>(new string[] {
	"AED: United Arab Emirates dirham",
	"AFN: Afghan afghani",
	"ALL: Albanian lek",
	"AMD: Armenian dram",
	"ANG: Netherlands Antillean guilder",
	"AOA: Angolan kwanza",
	"ARS: Argentine peso",
	"AUD: Australian dollar",
	"AWG: Aruban florin",
	"AZN: Azerbaijani manat",
	"BAM: Bosnia and Herzegovina convertible mark",
	"BBD: Barbados dollar",
	"BDT: Bangladeshi taka",
	"BGN: Bulgarian lev",
	"BHD: Bahraini dinar",
	"BMD: Bermudian dollar",
	"BND: Brunei dollar",
	"BOB: Boliviano",
	"BOV: Bolivian Mvdol",
	"BRL: Brazilian real",
	"BSD: Bahamian dollar",
	"BTN: Bhutanese ngultrum",
	"BWP: Botswana pula",
	"BYN: Belarusian ruble",
	"BZD: Belize dollar",
	"CAD: Canadian dollar",
	"CDF: Congolese franc",
	"CHE: WIR Euro",
	"CHF: Swiss franc",
	"CHW: WIR Franc",
	"CLF: Unidad de Fomento",
	"CNY: Renminbi",
	"COP: Colombian peso",
	"COU: Unidad de Valor Real",
	"CRC: Costa Rican colon",
	"CUC: Cuban convertible peso",
	"CUP: Cuban peso",
	"CZK: Czech koruna",
	"DKK: Danish krone",
	"DOP: Dominican peso",
	"DZD: Algerian dinar",
	"EGP: Egyptian pound",
	"ERN: Eritrean nakfa",
	"ETB: Ethiopian birr",
	"EUR: Euro",
	"FJD: Fiji dollar",
	"FKP: Falkland Islands pound",
	"GBP: Pound sterling",
	"GEL: Georgian lari",
	"GHS: Ghanaian cedi",
	"GIP: Gibraltar pound",
	"GMD: Gambian dalasi",
	"GTQ: Guatemalan quetzal",
	"GYD: Guyanese dollar",
	"HKD: Hong Kong dollar",
	"HNL: Honduran lempira",
	"HRK: Croatian kuna",
	"HTG: Haitian gourde",
	"HUF: Hungarian forint",
	"IDR: Indonesian rupiah",
	"ILS: Israeli new shekel",
	"INR: Indian rupee",
	"IQD: Iraqi dinar",
	"IRR: Iranian rial",
	"ISK: Icelandic krona",
	"JMD: Jamaican dollar",
	"JOD: Jordanian dinar",
	"KES: Kenyan shilling",
	"KGS: Kyrgyzstani som",
	"KHR: Cambodian riel",
	"KPW: North Korean won",
	"KWD: Kuwaiti dinar",
	"KYD: Cayman Islands dollar",
	"KZT: Kazakhstani tenge",
	"LAK: Lao kip",
	"LBP: Lebanese pound",
	"LKR: Sri Lankan rupee",
	"LRD: Liberian dollar",
	"LSL: Lesotho loti",
	"LYD: Libyan dinar",
	"MAD: Moroccan dirham",
	"MDL: Moldovan leu",
	"MGA: Malagasy ariary",
	"MKD: Macedonian denar",
	"MMK: Myanmar kyat",
	"MNT: Mongolian tögrög",
	"MOP: Macanese pataca",
	"MRU: Mauritanian ouguiya",
	"MUR: Mauritian rupee",
	"MVR: Maldivian rufiyaa",
	"MWK: Malawian kwacha",
	"MXN: Mexican peso",
	"MXV: Mexican Unidad de Inversion",
	"MYR: Malaysian ringgit",
	"MZN: Mozambican metical",
	"NAD: Namibian dollar",
	"NGN: Nigerian naira",
	"NIO: Nicaraguan cordoba",
	"NOK: Norwegian krone",
	"NPR: Nepalese rupee",
	"NZD: New Zealand dollar",
	"OMR: Omani rial",
	"PAB: Panamanian balboa",
	"PEN: Peruvian sol",
	"PGK: Papua New Guinean kina",
	"PHP: Philippine peso",
	"PKR: Pakistani rupee",
	"PLN: Polish zloty",
	"QAR: Qatari riyal",
	"RON: Romanian leu",
	"RSD: Serbian dinar",
	"RUB: Russian ruble",
	"SAR: Saudi riyal",
	"SBD: Solomon Islands dollar",
	"SCR: Seychelles rupee",
	"SDG: Sudanese pound",
	"SEK: Swedish krona",
	"SGD: Singapore dollar",
	"SHP: Saint Helena pound",
	"SLL: Sierra Leonean leone",
	"SOS: Somali shilling",
	"SRD: Surinamese dollar",
	"SSP: South Sudanese pound",
	"STN: Sao Tome and Principe dobra",
	"SVC: Salvadoran colon",
	"SYP: Syrian pound",
	"SZL: Swazi lilangeni",
	"THB: Thai baht",
	"TJS: Tajikistani somoni",
	"TMT: Turkmenistan manat",
	"TND: Tunisian dinar",
	"TOP: Tongan pa'anga",
	"TRY: Turkish lira",
	"TTD: Trinidad and Tobago dollar",
	"TWD: New Taiwan dollar",
	"TZS: Tanzanian shilling",
	"UAH: Ukrainian hryvnia",
	"UGX: Ugandan shilling",
	"USD: United States dollar",
	"USN: United States dollar (next day) ",
	"UYU: Uruguayan peso",
	"UYW: Unidad previsional",
	"UZS: Uzbekistan som",
	"VES: Venezuelan bolívar soberano",
	"WST: Samoan tala",
	"XCD: East Caribbean dollar",
	"YER: Yemeni rial",
	"ZAR: South African rand",
	"ZMW: Zambian kwacha",
	"ZWL: Zimbabwean dollar",
});
list.SetSource(items);
Application.Top.Add(list);
Application.Run();
```

**Comment by tznind** [comment]
Ah I see the issue, it is when the number of items is a multiple of the frame height

Fix is to change `MovePageDown` from:

```csharp
if (n > source.Count) 
     n = source.Count - 1; 
```

To:

```csharp
if (n >= source.Count) 
     n = source.Count - 1; 
```

**Comment by BDisp** [comment]
> Edit: ah looks like you already got there @BDisp :)

Yes :-) It only happen if it's a multiple of the frame height (`selected + Frame.Height == source.Count`). Do you think I should change for what you suggested?
