### ISSUE TITLE
TextView.TextChanging: Using Args.Cancel=true leads to System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by rmorales87atx** [migueldeicaza/gui.cs#1327]
Hello again 🙋‍♂️

I am setting up a `TextField` with a `TextChanging` event to validate the entry a user makes (the user should input an exact 3-character code, so once `args.NewText.Length` reaches `3` I run my validation).

When the user's input isn't valid, I set `args.Cancel` to `true` and call `MessageBox.ErrorQuery()` to display a message indicating the code isn't valid. After `MessageBox.ErrorQuery()` returns, two things happen:

1. The cursor disappears (no longer visible).
2. Pressing the Backspace key results in `System.ArgumentOutOfRangeException` being thrown.

```
System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.Collections.Generic.List`1.GetRange(Int32 index, Int32 count)
   at Terminal.Gui.TextField.ProcessKey(KeyEvent kb) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Views\TextField.cs:line 350
   at Terminal.Gui.View.ProcessHotKey(KeyEvent keyEvent) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\View.cs:line 1502
   at Terminal.Gui.Application.ProcessKeyEvent(KeyEvent ke) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 307
   at Terminal.Gui.WindowsDriver.ProcessInput(InputRecord inputEvent) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\ConsoleDrivers\WindowsDriver.cs:line 762
   at Terminal.Gui.WindowsDriver.<PrepareToRun>b__31_0(InputRecord e) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\ConsoleDrivers\WindowsDriver.cs:line 661
   at Terminal.Gui.WindowsMainLoop.Terminal.Gui.IMainLoopDriver.MainIteration() in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\ConsoleDrivers\WindowsDriver.cs:line 1634
   at Terminal.Gui.MainLoop.MainIteration() in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\MainLoop.cs:line 238
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 645
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 737
   at Terminal.Gui.Application.Run(Func`2 errorHandler) in E:\cashbox_cs\Terminal.Gui\Terminal.Gui\Core\Application.cs:line 687
```

`System.ArgumentOutOfRangeException` will not generate if I leave out `args.Cancel = true`; the cursor still remains invisible in this case.

Removing the call to `MessageBox.ErrorQuery()` and setting `args.Cancel` to `true` still results in `System.ArgumentOutOfRangeException`.

**Comment by tznind** [comment]
Here is a test case that reproduces the issue

```csharp
[Fact]
public void Cancel_TextChanging_ThenBackspace()
{			
	var tf = new TextField ();
	tf.EnsureFocus ();
	tf.ProcessKey (new KeyEvent (Key.A, new KeyModifiers ()));
	Assert.Equal ("A",tf.Text);

	// cancel the next keystroke
	tf.TextChanging += (e) => e.Cancel = true;
	tf.ProcessKey (new KeyEvent (Key.B, new KeyModifiers ()));

	// B was cancelled so should just be A
	Assert.Equal ("A", tf.Text);

	// now delete the A
	tf.ProcessKey (new KeyEvent (Key.Backspace, new KeyModifiers ()));

	Assert.Equal ("", tf.Text);
}
```

**Comment by tig** [comment]
> Here is a test case that reproduces the issue
> 
> ```cs
> [Fact]
> public void Cancel_TextChanging_ThenBackspace()
> {			
> 	var tf = new TextField ();
> 	tf.EnsureFocus ();
> 	tf.ProcessKey (new KeyEvent (Key.A, new KeyModifiers ()));
> 	Assert.Equal ("A",tf.Text);
> 
> 	// cancel the next keystroke
> 	tf.TextChanging += (e) => e.Cancel = e.NewText == "AB";
> 	tf.ProcessKey (new KeyEvent (Key.B, new KeyModifiers ()));
> 
> 	// B was cancelled so should just be A
> 	Assert.Equal ("A", tf.Text);
> 
> 	// now delete the A
> 	tf.ProcessKey (new KeyEvent (Key.Backspace, new KeyModifiers ()));
> 
> 	Assert.Equal ("", tf.Text);
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/31306100/120169741-2b73ed80-c1f8-11eb-87cb-987cac467dd7.png)

Here's @tznind raising the bar again on great engineering practices by posting an actual test case!
