### ISSUE TITLE
Unexpected difference between ListView and FrameView

### ISSUE THREAD

**Issue by En3Tho** [migueldeicaza/gui.cs#1469]
``` fsharp
open System
open NStack
open Terminal.Gui

let ustr (str: string) = ustring.op_Implicit str

let createApplication() =
    Application.Init()

    let top = Application.Top

    let window = new Window(
        X = Pos.At 0,
        Y = Pos.At 0,
        Width = Dim.Fill(),
        Height = Dim.Fill()
    )

    // same settings
    let keysFrameView = new FrameView(ustr "Keys",
        X = Pos.Left window,
        Y = Pos.Bottom window,
        Width = Dim.Fill(),
        Height = Dim.Percent(50.f)
    )
    
    // same settings
    let keysListView = new ListView(
        X = Pos.Left window,
        Y = Pos.Bottom window,
        Width = Dim.Fill(),
        Height = Dim.Percent(50.f)
    )

    keysListView.SetSource([|
        for _ = 0 to 32 do
            ustr (Guid.NewGuid().ToString())
    |])

    window.Add keysListView //  works
    // window.Add keysFrameView // comment prev, uncomment this -> doesn't work

    top.Add window

    Application.Run top

createApplication()
```

When adding listView everything works as expected
When adding frameView instead I get an exception (I modified it to show both edges instead of only one for clarity): 

Unhandled exception. System.InvalidOperationException: TopologicalSort (for Pos/Dim) cannot find link from Window()({X=0,Y=0,Width=80,Height=1}) to FrameView()({X=0,Y=0,Width=0,Height=0}). Did you forget
 to add it to ContentView()({X=1,Y=1,Width=78,Height=0})?
   at Terminal.Gui.View.TopologicalSort(HashSet`1 nodes, HashSet`1 edges) in H:\source\repos\En3Tho\gui.cs\Terminal.Gui\Core\View.cs:line 1875
   at Terminal.Gui.View.LayoutSubviews() in H:\source\repos\En3Tho\gui.cs\Terminal.Gui\Core\View.cs:line 2011
   at Terminal.Gui.View.LayoutSubviews() in H:\source\repos\En3Tho\gui.cs\Terminal.Gui\Core\View.cs:line 2018
   at Terminal.Gui.View.LayoutSubviews() in H:\source\repos\En3Tho\gui.cs\Terminal.Gui\Core\View.cs:line 2018
   at Terminal.Gui.Application.Begin(Toplevel toplevel) in H:\source\repos\En3Tho\gui.cs\Terminal.Gui\Core\Application.cs:line 733
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler) in H:\source\repos\En3Tho\gui.cs\Terminal.Gui\Core\Application.cs:line 1032
   at Program.createApplication() in H:\source\repos\En3Tho\gui.cs\FSharpExample3\Program.fs:line 41
   at <StartupCode$FSharpExample3>.$Program.main@() in H:\source\repos\En3Tho\gui.cs\FSharpExample3\Program.fs:line 43

Is there something I miss?

@tig @BDisp

**Comment by En3Tho** [comment]
When chash occures (with FrameView):
Nodes: FrameView
Edges: Window -> FrameView

When everything is ok (with ListView):
Nodes collection is empty and Edges collection is 1 element and vise versa.

**Comment by En3Tho** [comment]
Generally there are lots of strange things going on around FrameView ... Is it really this special?

**Comment by BDisp** [comment]
Because you are referencing  `Y = Pos.Bottom window`. First, you don't need to specify `X = Pos.Left window`, since it will assume `X = 0`, anyway. `FrameView` has a private `ContentView`, with `X=1,Y=1,Width=Width-2,Height=Height-2`, where will accommodate all his subviews.

I think you want this:
```fs
open System
open NStack
open Terminal.Gui

let ustr (str: string) = ustring.op_Implicit str

let createApplication() =
    Application.Init()

    let top = Application.Top

    let window = new Window(
        X = Pos.At 0,
        Y = Pos.At 0,
        Width = Dim.Fill(),
        Height = Dim.Fill()
    )

    // same settings
    let keysFrameView = new FrameView(ustr "Keys",
        //X = Pos.Left window,
        //Y = Pos.Bottom window,
        Width = Dim.Fill(),
        Height = Dim.Percent(50.f)
    )
    
    // same settings
    let keysListView = new ListView(
        //X = Pos.Left window,
        //Y = Pos.Bottom window,
        Y = Pos.Percent(50.f),
        Width = Dim.Fill(),
        //Height = Dim.Percent(50.f)
        Height = Dim.Fill()
    )

    keysListView.SetSource([|
        for _ = 0 to 32 do
            ustr (Guid.NewGuid().ToString())
    |])

    window.Add keysListView //  works
    window.Add keysFrameView // comment prev, uncomment this -> doesn't work

    top.Add window

    Application.Run top

createApplication()

```

or this:
```fs
open System
open NStack
open Terminal.Gui

let ustr (str: string) = ustring.op_Implicit str

let createApplication() =
    Application.Init()

    let top = Application.Top

    let window = new Window(
        X = Pos.At 0,
        Y = Pos.At 0,
        Width = Dim.Fill(),
        Height = Dim.Fill()
    )

    // same settings
    let keysFrameView = new FrameView(ustr "Keys",
        //X = Pos.Left window,
        //Y = Pos.Bottom window,
        Width = Dim.Fill(),
        Height = Dim.Percent(50.f)
    )
    
    // same settings
    let keysListView = new ListView(
        //X = Pos.Left window,
        //Y = Pos.Bottom window,
        Width = Dim.Fill(),
        //Height = Dim.Percent(50.f)
        Height = Dim.Fill()
    )

    keysListView.SetSource([|
        for _ = 0 to 32 do
            ustr (Guid.NewGuid().ToString())
    |])

    keysFrameView.Add keysListView //  works
    window.Add keysFrameView // comment prev, uncomment this -> doesn't work

    top.Add window

    Application.Run top

createApplication()

```

**Comment by En3Tho** [comment]
Sorry to bother and thanks for help, but what if I want to add multiple frameviews?
My problem now is: I want to make a simple RedisViewer for Powershell and I need to outline main components.
When I add commandText to commandFrameView it doesn't show up. When I hook to an event "TextChanged", it works. So basically there is an input but it jsut doesn't appear anywhere. Same with DB. Also, if I change dbTextfield with dbPickerComboBox I get the same exception. Can you please explain why is that? I guess I'm using FrameViews in a wrong fashion but why are they some different?
``` fsharp
open System
open NStack
open Terminal.Gui

let ustr (str: string) = ustring.op_Implicit str

let createApplication() =
    Application.Init()

    let top = Application.Top

    let window = new Window(
        X = Pos.At 0,
        Y = Pos.At 0,
        Width = Dim.Fill(),
        Height = Dim.Fill()
    )

    let filterFrameView = new FrameView(ustr "Filter",
        X = Pos.At 0,
        Y = Pos.At 0,
        Width = Dim.Percent(95.f),
        Height = Dim.Sized 3)

    // TODO: on enter search
    let filterTextField = new TextField(
        X = Pos.Left filterFrameView,
        Y = Pos.Top filterFrameView,
        Width = Dim.Fill(),
        Height = Dim.Fill(),
        Text = ustr "*"
    )

    let dbPickerFrameView = new FrameView(ustr "DB",
        X = Pos.Right filterFrameView,
        Y = Pos.Top filterFrameView,
        Width = Dim.Percent(5.f),
        Height = Dim.Sized 3)

    // TODO: on enter search
    let dbTextField = new TextField(
        X = Pos.Left dbPickerFrameView,
        Y = Pos.Top dbPickerFrameView,
        Width = Dim.Fill(),
        Height = Dim.Fill(),
        Text = ustr "*"
    )

    let dbPickerComboBox = new ComboBox(
        X = Pos.Left dbPickerFrameView,
        Y = Pos.Top dbPickerFrameView,
        Width = Dim.Fill(),
        Height = Dim.Sized 16
    )

    dbPickerComboBox.SetSource([|
        for i = 0 to 15 do ustr (string i)
    |])

    let keysFrameView = new FrameView(ustr "Keys",
        X = Pos.Left filterFrameView,
        Y = Pos.Bottom filterFrameView,
        Width = Dim.Fill(),
        Height = Dim.Percent(50.f) - Dim.Sized 3
    )

    let keysListView = new ListView(
        X = Pos.Left keysFrameView,
        Y = Pos.Bottom keysFrameView,
        Width = Dim.Fill(),
        Height = Dim.Fill()
    )

    keysListView.SetSource([|
        for _ = 0 to 32 do
            ustr (Guid.NewGuid().ToString())
    |])

    let resultsFrameView = new FrameView(ustr "Results",
        X = Pos.Left keysFrameView,
        Y = Pos.Bottom keysFrameView,
        Width = Dim.Fill(),
        Height = Dim.Fill() - Dim.Sized 3
    )

    let resultListView = new ListView(
        X = Pos.At 0,
        Y = Pos.At 0,
        Width = Dim.Fill(),
        Height = Dim.Fill()
    )

    resultListView.SetSource([|
        for _ = 0 to 32 do
            ustr (Guid.NewGuid().ToString())
    |])

    let commandFrameView = new FrameView(ustr "Command",
        X = Pos.Left resultsFrameView,
        Y = Pos.Bottom resultsFrameView,
        Width = Dim.Fill(),
        Height = Dim.Sized 3
    )

    let commandTextField = new TextField(
        X = Pos.Left commandFrameView,
        Y = Pos.Top commandFrameView,
        Width = Dim.Fill(),
        Height = Dim.Fill(),
        Text = ustr "*"
    )

    // Top row
    filterFrameView.Add filterTextField
    dbPickerFrameView.Add dbTextField
    window.Add filterFrameView
    window.Add dbPickerFrameView

    // Middle
    keysFrameView.Add keysListView
    window.Add keysFrameView

    resultsFrameView.Add resultListView
    window.Add resultsFrameView

    // Bottom row
    commandFrameView.Add commandTextField
    window.Add commandFrameView

    top.Add window

    Application.Run top

createApplication()
```

**Comment by En3Tho** [comment]
![image](https://user-images.githubusercontent.com/37334640/134680573-284b3b01-604a-4782-a379-b9db31d31a5e.png)
It looks neat and I just need a small push to complete it...

**Comment by En3Tho** [comment]
It helped. Big thanks. Seems like many of those assignments were indeed useless. Can you please help me with displaying ComboBox in full size inside frameview? Is it possible or FrameView simply limits the ComboBox?

**Comment by En3Tho** [comment]
@BDisp Sorry to nag/tag. Can you please tell if it's possible? (the question above)

**Comment by BDisp** [comment]
If you are adding the `ComboBox` to the `dbPickerFrameView`, the combo box (height=16) cannot be accommodated in the frame view with height of 3. If you are adding subviews to another view, you cannot reference the superview in the subviews.

**Comment by En3Tho** [comment]
@BDisp I see. Sorry for bothering with newbie questions. It looks like this now. Big thanks!
![image](https://user-images.githubusercontent.com/37334640/134735971-178345d4-4eb1-4a89-b3f9-2fecf0258e7e.png)

**Comment by BDisp** [comment]
Because the `ComboBox` must be added to the `Window` there is needed more some work to show the `ComboBox` at start.

```fs
open System
open NStack
open Terminal.Gui

let ustr (str: string) = ustring.op_Implicit str

let createApplication() =
    Application.Init()

    let top = Application.Top

    let window = new Window(
        X = Pos.At 0,
        Y = Pos.At 0,
        Width = Dim.Fill(),
        Height = Dim.Fill()
    )

    let filterFrameView = new FrameView(ustr "Filter",
        X = Pos.At 0,
        Y = Pos.At 0,
        Width = Dim.Percent(90.f),
        Height = Dim.Sized 3
    )

    // TODO: on enter search
    let filterTextField = new TextField(
        //X = Pos.Left filterFrameView,
        //Y = Pos.Top filterFrameView,
        Width = Dim.Fill(),
        Height = Dim.Fill(),
        Text = ustr "*"
    )

    let dbPickerFrameView = new FrameView(ustr "DB",
        X = Pos.Right filterFrameView,
        Y = Pos.Top filterFrameView,
        Width = Dim.Fill(),
        Height = Dim.Sized 3)

    // TODO: on enter search
    let dbTextField = new TextField(
        //X = Pos.Left dbPickerFrameView,
        //Y = Pos.Top dbPickerFrameView,
        Width = Dim.Fill(),
        Height = Dim.Fill(),
        Text = ustr "*"
    )

    let dbPickerComboBox = new ComboBox(
        X = Pos.Left dbPickerFrameView + Pos.At 1,
        Y = Pos.Top dbPickerFrameView + Pos.At 1,
        Width = Dim.Fill(1),
        Height = Dim.Sized 16
    )
    
    dbPickerComboBox.SetSource([|
        for i = 0 to 15 do ustr (string i)
    |])

    //dbPickerFrameView.add_DrawContent(Action<Rect>(
    //    fun e ->
    //        dbPickerComboBox.SetNeedsDisplay()
    //        dbPickerComboBox.Redraw(e)))

    let keysFrameView = new FrameView(ustr "Keys",
        X = Pos.Left filterFrameView,
        Y = Pos.Bottom filterFrameView,
        Width = Dim.Fill(),
        Height = Dim.Percent(50.f) - Dim.Sized 3
    )

    let keysListView = new ListView(
        //X = Pos.Left keysFrameView,
        //Y = Pos.Bottom keysFrameView,
        Width = Dim.Fill(),
        Height = Dim.Fill()
    )

    keysListView.SetSource([|
        for _ = 0 to 32 do
            ustr (Guid.NewGuid().ToString())
    |])

    let resultsFrameView = new FrameView(ustr "Results",
        X = Pos.Left keysFrameView,
        Y = Pos.Bottom keysFrameView,
        Width = Dim.Fill(),
        Height = Dim.Fill() - Dim.Sized 3
    )

    let resultListView = new ListView(
        //X = Pos.At 0,
        //Y = Pos.At 0,
        Width = Dim.Fill(),
        Height = Dim.Fill()
    )

    resultListView.SetSource([|
        for _ = 0 to 32 do
            ustr (Guid.NewGuid().ToString())
    |])

    let commandFrameView = new FrameView(ustr "Command",
        X = Pos.Left resultsFrameView,
        Y = Pos.Bottom resultsFrameView,
        Width = Dim.Fill(),
        Height = Dim.Sized 3
    )

    let commandTextField = new TextField(
        //X = Pos.Left commandFrameView,
        //Y = Pos.Top commandFrameView,
        Width = Dim.Fill(),
        Height = Dim.Fill(),
        Text = ustr "*"
    )

    // Top row
    filterFrameView.Add filterTextField
    //dbPickerFrameView.Add dbTextField // added but doesn't show up, if changed to dbPickerComboBox, crashes
    window.Add filterFrameView
    window.Add dbPickerComboBox // added but doesn't show up, if changed to dbPickerComboBox, crashes
    window.Add dbPickerFrameView

    // Middle
    keysFrameView.Add keysListView
    window.Add keysFrameView

    resultsFrameView.Add resultListView
    window.Add resultsFrameView

    // Bottom row
    commandFrameView.Add commandTextField  // added but doesn't show up
    window.Add commandFrameView
    window.Subviews.[0].BringSubviewToFront(dbPickerComboBox)
    top.Add window

    Application.Run top

createApplication()

```

![combobox](https://user-images.githubusercontent.com/13117724/134749597-ceac5346-78ba-48e5-b2da-bdecc356747d.gif)

**Comment by En3Tho** [comment]
Neat 🙂. Thanks! Going to update my crutchy half-baked db picker :)
