### ISSUE TITLE
View crashes when trying to get seleciton when last char is " "

### ISSUE THREAD

**Issue by En3Tho** [migueldeicaza/gui.cs#1475]
How to reproduce:
Set last char of TextField (or ComboBox or maybe other views) text to " " then double click at next position.

Reproduceable both on main and nuget version.
PrepareSelection method passes invalid parameters to String.SubString resulting an exception.

As I've understood, selection tries to ignore whitespace but there are some quircks, for example:

" abc " 
 ^ - if double click is called on first char then full string is selected

" abc " 
        ^ - if double click is called on last char "abc " is selected

" abc " 
         ^ - if double click is called on next after last char position then exception is thrown

It is easily reproduceable when the only char is " ". The code below then has start = 1 and length = 2 which results in exception. So I guess start = 1 is ok, but length of 2 is not. Considering text itself has 1 char only.
![image](https://user-images.githubusercontent.com/37334640/135311253-9d48a712-f542-41a3-898b-b84b2cebc5f0.png)

**Comment by En3Tho** [comment]
@tig @BDisp @tznind Can someone provide me with some info regarding how selection should work in this case? I've took your time with my questions and issues, I want to provide some value back :)

**Comment by tznind** [comment]
Sorry I've not really used ComboBox or experienced this bug.  Is it possible to write a unit test that demonstrates the bug? We should definetly fix an unhandled exception double clicking in the control!

I think it would be quite a lot of work to migrate to nullable reference types across the board but I understand that it can be turned on for specific files by using `#nullable enable` so that might be an option.

I think we should seperate these two issues though.  Maybe raise a discussion thread about NRT?

**Comment by En3Tho** [comment]
It's not only with ComboBox, TextView is affected too. All you have to do is to put " " at the end of the line and double click at next position.

**Comment by tznind** [comment]
Here is a test that demonstrates it

```csharp
[Fact]
[InitShutdown]
public void TextField_SpaceHandling()
{
    var tf = new TextField(){
        Width = 10,
        Text = " "
    };

    MouseEvent ev = new MouseEvent()
    {
        X = 0,
        Y = 0,
        Flags = MouseFlags.Button1DoubleClicked,
    };

    tf.MouseEvent (ev);

    ev = new MouseEvent()
    {
        X = 1,
        Y = 0,
        Flags = MouseFlags.Button1DoubleClicked,
    };
    
    tf.MouseEvent (ev);
}
```

Exception:
```
dling [FAIL]
  Failed Terminal.Gui.Views.TextFieldTests.TextField_SpaceHandling [9 ms]
  Error Message:
   System.ArgumentOutOfRangeException : Index and length must refer to a location within the string. (Parameter 'length')
  Stack Trace:
     at System.String.Substring(Int32 startIndex, Int32 length)
   at Terminal.Gui.TextField.PrepareSelection(Int32 x, Int32 direction) in /home/thomas/gui.cs/Terminal.Gui/Views/TextField.cs:line 815
   at Terminal.Gui.TextField.MouseEvent(MouseEvent ev) in /home/thomas/gui.cs/Terminal.Gui/Views/TextField.cs:line 766
   at Terminal.Gui.Views.TextFieldTests.TextField_SpaceHandling() in /home/thomas/gui.cs/UnitTests/TextFieldTests.cs:line 815
```

**Comment by tig** [comment]
Damn, @tznind, you continue to set the bar for how to treat bug reports. I love how, by providing test cases, you are 

a) teaching others how to fish
b) ensuring the entire project is always getting better. 

Huge kudos!

**Comment by BDisp** [comment]
Sorry for my absence on this issue. Thanks @En3Tho for reporting this. I couldn't reproduce the issue with the mouse.
Thanks @tznind for the unit test which reproduces successfully the issue reported.
I will try to fix this.

**Comment by BDisp** [comment]
> [SideNote] Also, while I was fixing #1472 a question arised: what is the cost of migrating to C# 9 with NRT? It could help tremendously with such bugs

It would be great but @migueldeicaza needs support for the Net.Framework. I do not know if it would be compatible.
