### ISSUE TITLE
UseSystemConsole: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by dustinlacewell** [migueldeicaza/gui.cs#1576]
Running the StandaloneExample with UseSystemConsole = true I get:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.Toplevel.Redraw(Rect region)
   at Terminal.Gui.Application.Redraw(View view)
   at Terminal.Gui.Application.Begin(Toplevel toplevel)
   at Terminal.Gui.Application.Run(Toplevel view)
   at Terminal.Gui.Application.Run()
   at Demo.Main() in /home/ldlework/ext/gui.cs/StandaloneExample/Program.cs:line 212
   ```

**Comment by BDisp** [comment]
The `StandaloneExample` isn't updated for a long time ago. You have to update the `Terminal.Gui` nuget package to the last version.

**Comment by tig** [comment]
We should either fix the sample or nuke it.
