### ISSUE TITLE
Azure Kudu support?

### ISSUE THREAD

**Issue by smourier** [migueldeicaza/gui.cs#241]
Hi!

Today, this great library doesn't work in Microsoft Azure Kudu (or did I miss something?) : https://blogs.msdn.microsoft.com/benjaminperkins/2014/03/24/using-kudu-with-windows-azure-web-sites/

The stack is like this:

```
Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_WindowWidth()
   at Terminal.Gui.WindowsDriver..ctor()
   at Terminal.Gui.Application.Init()
   at ConsoleApp2.Program.Main(String[] args) in D:\smo\source\repos\ConsoleApplication4\ConsoleApp3\Program.cs:line 12
```

Is it possible to make it work? Or is guid.cs definitely tied to a desktop?
Thanks.

**Comment by migueldeicaza** [comment]
I am confused - what is this running under?

This looks like Windows, shouldn't Windows support this?   How are .NET console applications supposed to run on that environment?

**Comment by smourier** [comment]
I'm not sure, but Console apps do work in that environment.

Maybe these apps are launched with ProcessStartInfo.CreateNoWindow = true so they don't get a Window handle at all, so they only have streams in, out, etc.?

Maybe it means we'll never be able to use gui.cs in this environement...

**Comment by migueldeicaza** [comment]
Closing until more information is available
