### ISSUE TITLE
Application.Run(new Window("test"));   -> null exception

### ISSUE THREAD

**Issue by paillave** [migueldeicaza/gui.cs#334]
I don't understand why `Application.Run(new Window("test"));` throws the following exception:

```
Exception thrown: 'System.NullReferenceException' in Terminal.Gui.dll: 'Object reference not set to an instance of an object.'
   at Terminal.Gui.Window.Redraw(Rect bounds)
   at Terminal.Gui.Application.Redraw(View view)
   at Terminal.Gui.Application.Begin(Toplevel toplevel)
   at Terminal.Gui.Application.Run(Toplevel view)
```

**Comment by paillave** [comment]
ok must make `Application.Init();` before
