### ISSUE TITLE
Windows: Resize window causes stack trace

### ISSUE THREAD

**Issue by mbalsam** [migueldeicaza/gui.cs#66]
If you open terminal in a dos or powershell window and resize the window you get this stacktrace

`Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terminal.Gui.NetDriver.Refresh() in C:\dev\gui.cs-master\Terminal.Gui\Driver.cs:line 1009
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait) in C:\dev\gui.cs-master\Terminal.Gui\Core.cs:line 1547
   at Terminal.Gui.Application.Run(Toplevel view) in C:\dev\gui.cs-master\Terminal.Gui\Core.cs:line 1600 
   at Terminal.Gui.Application.Run() in C:\dev\gui.cs-master\Terminal.Gui\Core.cs:line 1569
   at Demo.Main() in C:\dev\gui.cs-master\demo.cs:line 225`

BTW, great project..

**Comment by migueldeicaza** [comment]
Looks like the driver needs to catch the window resize event, like this:

https://stackoverflow.com/questions/11361811/capture-all-windows-messages

**Comment by mbalsam** [comment]
If you like, we can take a crack at it?

**Comment by migueldeicaza** [comment]
Sure, I just checked in some code that provides the interface to the Windows APIs, and it now needs to be wired up, going to sleep now, feel free to take it from here - if not I will try to check tomrorow,

**Comment by mbalsam** [comment]
I looked at it and it was above my pay grade..   Thanks for the fix...

**Comment by migueldeicaza** [comment]
Fixed by @nickvdyck pull request.
