### ISSUE TITLE
Doesn't work with .NET 5 single file apps

### ISSUE THREAD

**Issue by MichalStrehovsky** [migueldeicaza/gui.cs#889]
Follow instructions at https://github.com/benaadams/gui-linked to publish as a single file on Linux.

libcoreclr.so is an internal implementation detail of the .NET runtime. It shouldn't be depended on by 3rd party code.

```
Curses failed to initialize, the exception is: System.DllNotFoundException: Unable to load shared library 'libcoreclr.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibcoreclr.so: cannot open shared object file: No such file or directory
   at Mono.Terminal.Internal.UnmanagedLibrary.CoreCLR.dlopen(String filename, Int32 flags)
   at Mono.Terminal.Internal.UnmanagedLibrary.PlatformSpecificLoadLibrary(String libraryPath)
   at Mono.Terminal.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives, Boolean isFullPath)
   at Unix.Terminal.Curses.LoadMethods()
   at Unix.Terminal.Curses.FindNCurses()
   at Unix.Terminal.Curses.initscr()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Unix.Terminal.Curses.raw()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)
   at Terminal.Gui.Application.Init(Func`1 topLevelFactory)
   at Terminal.Gui.Application.Init()
   at Demo.Main()
Aborted
```

**Comment by benaadams** [comment]
https://github.com/migueldeicaza/gui.cs/blob/91a86c9460751dd0ed40ee8945b12f6cdb33b5fd/Terminal.Gui/ConsoleDrivers/CursesDriver/UnmanagedLibrary.cs#L179-L197

https://github.com/migueldeicaza/gui.cs/blob/91a86c9460751dd0ed40ee8945b12f6cdb33b5fd/Terminal.Gui/ConsoleDrivers/CursesDriver/UnmanagedLibrary.cs#L254-L266

**Comment by Mgamerz** [comment]
Tested this on my end, also doesn't work on .net 5 with single file mode.
